// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGMb8vZQANGpX-rBnx3RodIsizFRyn9w0',
    appId: '1:687340516426:web:fb3f33e7e9115d94a662b3',
    messagingSenderId: '687340516426',
    projectId: 'techhub-ce792',
    authDomain: 'techhub-ce792.firebaseapp.com',
    databaseURL: 'https://techhub-ce792-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techhub-ce792.appspot.com',
    measurementId: 'G-47M86KHL04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVRjQiWP6YuLl6oSUuTv5d3K6yErNJfpw',
    appId: '1:687340516426:android:0807f9c75e771622a662b3',
    messagingSenderId: '687340516426',
    projectId: 'techhub-ce792',
    databaseURL: 'https://techhub-ce792-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techhub-ce792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnljVnLKBCmGLaN280LqZP802OST9YwqE',
    appId: '1:687340516426:ios:422f8edf009dd1e8a662b3',
    messagingSenderId: '687340516426',
    projectId: 'techhub-ce792',
    databaseURL: 'https://techhub-ce792-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techhub-ce792.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnljVnLKBCmGLaN280LqZP802OST9YwqE',
    appId: '1:687340516426:ios:c116907ef041ee80a662b3',
    messagingSenderId: '687340516426',
    projectId: 'techhub-ce792',
    databaseURL: 'https://techhub-ce792-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techhub-ce792.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
